name = input("Name:")
age = input("Age:")
course = input("Course:")
contact = input("Phone:")
print("The name you have entered is :",name)
print("")
print("The age you have entered is :",age)
print("")
print("The course you have entered is :",course)
print("")
print("Your phone number is :",contact)
print("")
i = int(input("To confirm enter 1:"))
if i == 1 :
    print("Welcome to Netzwerk Academy")
else :
    print("PLease enter the correct inputs")
